server:
  port: 9082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dubbo_vendor?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: root

      